name: Notify ntfy on push
on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send notification to ntfy
        env:
          AUTH: ${{ secrets.NTFY_AUTH }}
        run: |
          curl -u ":tk_gr92hj0xknad85rtye7rkfbwc95jq" \
            -d "Nouvelle mise à jour du site Villa Marguerite ! Message d'ajout : ${{ github.event.head_commit.message }} 
            Rendez-vous sur le site : https://villa-marguerite.vercel.app/" \
            https://ntfy.sh/villa-marguerite