name: Bump package.json version on merge to main

on:
  pull_request:
    types: [closed]     # déclenché quand le PR se ferme
    branches: [main]    # base = main

jobs:
  bump:
    if: ${{ github.event.pull_request.merged == true }}  # seulement si MERGED
    runs-on: ubuntu-latest
    permissions:
      contents: write                                   # nécessaire pour push

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bump patch version
        run: |
          npm version patch --no-git-tag-version

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "⬆️ bump version after merge [skip ci]" || exit 0
          git push origin HEAD:main
