name: Bump package.json version on merge to main

on:
  pull_request:
    types: [closed]
    branches: [main]

jobs:
  bump:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Ensure up-to-date main
        run: |
          git fetch origin main
          git checkout main
          git pull --ff-only origin main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bump patch version
        run: |
          npm version patch --no-git-tag-version

      - name: Commit & push version bump
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "⬆️ bump version after merge of #${{ github.event.pull_request.number }} [skip ci]" || exit 0
          git push origin HEAD:main
