name: Bump package.json version on push to main

on:
  push:
    branches: [main]

jobs:
  bump:
    # évite de re-déclencher le workflow sur le commit "bump version"
    if: ${{ !contains(github.event.head_commit.message, 'bump version') }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Bump patch version
        run: npm version patch --no-git-tag-version

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json || true
          git commit -m "⬆️ bump version [skip ci]" || exit 0
          git push
